Upgrade node-gyp package to fix Python 3.12 issue
Fix an issue for Python 3.12 and node-gyp where node-gyp relies on the
"distutils" package in Python, which was removed in 3.12.

It resulted in this error upon install:

```
Traceback (most recent call last):
  File "/Users/tombruijn/appsignal/nodejs/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File "/Users/tombruijn/appsignal/nodejs/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    import gyp.input
  File "/Users/tombruijn/appsignal/nodejs/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
```

Upgrade node-gyp to resolve this issue.

Related issue in node-gyp:
https://github.com/nodejs/node-gyp/issues/2869